// Copyright 2010 Peter Stegemann

#pragma once

#include "Types.h"

#define SIGNAL_MAXIMUM_VALUE		30000L
#define SIGNAL_NEUTRAL_VALUE		0L
#define SIGNAL_MINIMUM_VALUE		( - SIGNAL_MAXIMUM_VALUE)
#define SIGNAL_VALUE_RANGE			( SIGNAL_MAXIMUM_VALUE - SIGNAL_MINIMUM_VALUE)

#define SIGNAL_LIMITS				2
#define SIGNAL_TRIMS				4
