// Copyright 2021 Peter Stegemann

#pragma once

#define SIGNAL_TRIM_STEPS_PER_SIDE    50

#define SIGNAL_TRIM_MAXIMUM_VALUE     SIGNAL_TRIM_STEPS_PER_SIDE
#define SIGNAL_TRIM_NEUTRAL_VALUE     0
#define SIGNAL_TRIM_MINIMUM_VALUE     ( - SIGNAL_TRIM_STEPS_PER_SIDE)
#define SIGNAL_TRIM_VALUE_RANGE       ( SIGNAL_TRIM_MAXIMUM_VALUE - SIGNAL_TRIM_MINIMUM_VALUE)
