// Copyright 2008 Peter Stegemann

#pragma once

#include "Output_Defines.h"
#include "Setup_Calibration.h"
#include "Setup_Output.h"
#include "Setup_Trim.h"
#include "Signal_Defines.h"
#include "Signal_Defines_Calibration.h"
#include "Signal_Defines_Trim.h"
#include "System_Ports.h"

#include <avr/eeprom.h>

struct Setup
{
	uint8_t InvertedPPM;

	Setup_Calibration Calibration[ INPUT_ANALOG_PORTS];
	Setup_Trim Trim[ SIGNAL_TRIMS];
	Setup_Output Output[ OUTPUT_CHANNELS];
};

Setup Eeprom EEMEM =
{
	0,

	{
		{
      SIGNAL_CALIBRATION_MAXIMUM_VALUE,
      SIGNAL_CALIBRATION_NEUTRAL_VALUE,
      SIGNAL_CALIBRATION_MINIMUM_VALUE
    },
		{
      SIGNAL_CALIBRATION_MAXIMUM_VALUE,
      SIGNAL_CALIBRATION_NEUTRAL_VALUE,
      SIGNAL_CALIBRATION_MINIMUM_VALUE
    },
		{
      SIGNAL_CALIBRATION_MAXIMUM_VALUE,
      SIGNAL_CALIBRATION_NEUTRAL_VALUE,
      SIGNAL_CALIBRATION_MINIMUM_VALUE
    },
		{
      SIGNAL_CALIBRATION_MAXIMUM_VALUE,
      SIGNAL_CALIBRATION_NEUTRAL_VALUE,
      SIGNAL_CALIBRATION_MINIMUM_VALUE
    },
		{
      SIGNAL_CALIBRATION_MAXIMUM_VALUE,
      SIGNAL_CALIBRATION_NEUTRAL_VALUE,
      SIGNAL_CALIBRATION_MINIMUM_VALUE
    }
	},

	{
		{ SIGNAL_TRIM_NEUTRAL_VALUE},
		{ SIGNAL_TRIM_NEUTRAL_VALUE},
		{ SIGNAL_TRIM_NEUTRAL_VALUE},
		{ SIGNAL_TRIM_NEUTRAL_VALUE}
	},

	{
		{ 0, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false},
		{ 1, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false},
		{ 2, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false},
		{ 3, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false},
		{ 4, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false},
		{ 5, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false},
#if defined( OUTPUT_PPM)
		{ 6, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false},
		{ 7, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false},
		{ 8, SIGNAL_MAXIMUM_VALUE, SIGNAL_NEUTRAL_VALUE, SIGNAL_MINIMUM_VALUE, false}
#endif
	}
};
